### ISSUE TITLE
Reuse the method on CHX only data

### ISSUE THREAD

**Issue by boboppie** [alexfields/ORF-RATER#1]
Dear Alex,

Thank you for contributing a great method to the community. We are very interested to apply your algorithm to our data. However, we only have cycloheximide treated datasets. By reading the source code, it seems I can still reuse the code directly to CHX data without modification, is that the case?

It was mentioned in your paper that a modified algorithm was applied to ND only datasets. Have you tried it on CHX only? What do you expect to see in the results in terms of performance and accuracy? If I have to modify the code for CHX only, could you point me out how to do it?

Another question is regarding the classification and monotonization. You have selected six features to train the classifier including Wald statistics for the genomic start of Harr, LTM and CHX/ND, etc. As in our case, Harr and LTM features will not be available. Is the code needed to be modified to cope with this? In your training set, ORFs  >= 100aa are selected. What about small ORFs below the threshold? I had a hard time to interpret _rate_regression_output.py_, your advice is greatly appreciated.

Best wishes,
Fengyuan

**Comment by alexfields** [comment]
Hi Fengyuan,

It should be no problem to run the code on CHX data alone without modification. Please let me know if you encounter any difficulty with that.

As you mentioned, I have run the code on ND only data, but not on CHX only data. From our own data in mouse, CHX treatment results in some loss of three-nucleotide periodicity, meaning that it will be more challenging to disambiguate translation of overlapping reading frames. It is difficult to predict performance and accuracy, as these depend on many dataset-specific parameters such as sequencing depth, transcriptome complexity, and the precise pattern of reads within CDSs. It will likely be simplest to try it and see - the software reports the accuracy achieved by the random forest estimator, so if it reports a poor value, that's an indication that the results are less reliable.

Regarding classification and monotonization, the classifier will select the features appropriate to the datasets included, so if only CHX data are available, it will only use the features derived from that dataset. Again, the accuracy the classifier reports should give a sense of the reliability of the output.

As you mentioned, the training set I used selects ATG-initiated ORFs of length >= 100aa. I excluded smaller ORFs from training because there are very few positive annotations for CDSs of that size, so I worried that I would be specifically training against short ORFs. That exception only applies to training; for classification, ORFs of all sizes are considered. You can override the minimum ORF length in the training set using the --goldminlen parameter in rate_regression_output.py.

Please let me know if you have any further questions or issues.

Best,
Alex
