### ISSUE TITLE
Regarding prune transcripts

### ISSUE THREAD

**Issue by boboppie** [alexfields/ORF-RATER#3]
Dear Alex,

In you paper, you aligned the footprints to a BMDC-specific transcriptome firstly, and then to UCSC annotated transcripts for those not aligned. In my case, I do not have an assembled transcriptome for our data (reconstructing transcriptome is not trivial), so I just aligned all the reads to annotated transcripts at the expense of losing true signals. Then I quantified the transcript expressions, giving raw read counts 10 (based on experience of our bioinformation) as a cut-off for expression, I can filter out most of the transcripts (non-expressed) before running prune_transcripts.py. Do you think it's reasonable?

In prune_transcripts.py, you have set 64 as the min raw read counts for each transcript (as well as in TopHat max multihits), how did you decide to use this number?

For peakfrac, you excluded transcripts that have 1/5 or more of the reads aligned to a single position. it's known that Ribosome Profiling shows peaks over start codons. Will preakfrac possibly rule out good transcripts that have 1/5 or more reads aligned around start codons?

Thanks,
Fengyuan

**Comment by alexfields** [comment]
Hi Fengyuan,

Anything you can do to constrain the transcripts you're considering is probably worthwhile, so your filtering plan seems reasonable. On the other hand, it probably won't matter very much, because those transcripts would be filtered out by prune_transcripts.py anyway.

The choice of 64 as the cutoff for read counts was fairly arbitrary. Some of the other people in my lab have used 128 in the past, so 64 was an attempt to be a bit more permissive. When there are too few counts, the pattern of read density becomes too noisy to identify patterns well, but there isn't a precise value at which this problem becomes dominant, and I haven't systematically searched for an optimal cutoff.

For the max multihits in TopHat, I wanted a number high enough that all multiple alignments would be reported. 64 achieved this goal (i.e., there were no reads with greater than that number of alignment positions). It is just a coincidence that it is the same number as the expression cutoff.

You're correct that peakfrac might eliminate transcripts with particularly dominant peaks at the start codon, but this is quite unlikely in a no-drug or CHX sample. On the other hand, I've recently realized that including this filter may be unnecessary anyway. I originally created the peakfrac filter because I noticed that there were some transcripts with a small number of positions that contained all of the reads, and I wanted to eliminate those transcripts before proceeding. More recently, I tried running the pipeline without using this filter (i.e. setting peakfrac = 1), and didn't see any degradation in performance. So maybe it's not as useful as I originally thought.

Please don't hesitate to ask if you have more questions, and I'd be curious to hear about your experience using the pipeline.

Best,
Alex
