### ISSUE TITLE
prune_transcripts

### ISSUE THREAD

**Issue by cfblaeb** [alexfields/ORF-RATER#4]
There is an unmentioned dependency on tables.
It is not python3 compatible due to tuble parameter unpacking (https://www.python.org/dev/peps/pep-3113/) . Can probably be automatically fixed with 2to3

**Comment by cfblaeb** [comment]
Also unmentioned dependency on python-igraph (not to be confused with renamed project still in pypi as igraph) in rate_regression_output

**Comment by alexfields** [comment]
I updated the readme to indicate/correct the dependencies. I also removed all tuple parameter unpacking in accordance with PEP 3113. Python 3 compatibility is untested but doubtful (e.g. due to dict.iteritems() and probably other problems). Thank you for pointing out these issues, and please let me know if you notice any others.
