### ISSUE TITLE
Unique hits and combine biological replicates

### ISSUE THREAD

**Issue by boboppie** [alexfields/ORF-RATER#5]
Hi Alex,

I have a couple of questions:

Why did you allow multiple hits in your alignment? Will it increase false positive signals.

In my case, I only kept uniquely aligned reads, however it resulted in much fewer reads than I expected (a large proportion of reads had been removed as contaminants). I'm thinking to combine all biological replicates to increase depth. Does it make sense?

Thanks,
Fengyuan

**Comment by alexfields** [comment]
Hi Fengyuan,

I allowed for multiple hits in the alignment because I wanted to use the profiling results to disambiguate between transcripts that share sequence identity. In many cases, even if a sequence appears in several places in the genome, only one is actually translated, and the presence or absence of nearby unique alignments can indicate which transcript is the translated one. This is one of the intended functions of prune_transcripts.py. Additionally, if only uniquely aligned positions are included, then there will be many positions within transcripts that are lacking reads completely, resulting in a pattern that does not fit well to the expected read profile.

A more conservative strategy could have been to mask out all multimapping positions so they are not included in the fit at all, with the downside that some ORFs would simply be unable to be fit (e.g. if all or nearly all positions multimap with another transcript). But because ORF-RATER as currently implemented is expecting all positions to have aligned reads (or at least to have the possibility of having aligned reads), it will likely perform poorly if only unique alignments are allowed. Perhaps the best option would have been to actually perform the regression simultaneously for all transcripts that include positions with sequence identity (allowing those positions to include contributions from translation on multiple transcripts), but this would require some significant reworking of the code. I have no plans at present to implement either of these strategies, so I would recommend reporting multimappers in your alignment if you wish to use ORF-RATER.

If your read depth seems too low, combining replicates definitely makes sense. For the paper, we combined all of the time points when running ORF-RATER. Pooling alignments offers a tradeoff between improving the specificity because of greater read depth (and thus lower noise), but possibly losing sensitivity to CDSs that are only translated in one or a subset of the pooled samples.

Best,
Alex
